// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}
  # Project Title 🗂: 

  ## Contact information 📮:
  Contact the Developer of this project via
  
  ## Description 📜 
  Brief overview: 
  
  ## License 🪪 and badge 🛡
  The {liscence} liscence has been selected for this project. {badge}
  
  ## Motivation 💪🏻
  We built this project to 
  
  ## Installation 🛠
  Follow these simple step-by-step instructions for installing the project code. 
  
  ## Usage 🥡🥢
  You can use this repository and code by: 
  
  ## Contributing 💃🏻🕺🏼 
  You can contribute to this repository by 
  
  ## Further Issues 🚨
  Any issues with this repository please contact the repository owner. 
  
  
  This README file has been generated by FeedTheRead 🥙😋🗒
`;
}

module.exports = generateMarkdown;
