// TODO: Create a function that returns a license badge based on which license is passed in

const { default: CheckboxPrompt } = require("inquirer/lib/prompts/checkbox");

// If there is no license, return an empty string
function renderLicenseBadge(license) {
  let licenseChosen = license
  let licenseBadge = '';

  if (licenseChosen === 'Apache 2.0'){
    licenseBadge = `![Apache License](https://img.shields.io/badge/License-Apache%202.0-red.png)`
  } else if(licenseChosen === 'Eclipse Public') {
    licenseBadge = `![Eclipse License](https://img.shields.io/badge/License-Eclipse%20Public-yellow.png)`
  } else if (licenseChosen === 'MIT'){
    licenseBadge = `![MIT license](https://img.shields.io/badge/License-MIT-green.png)`
  }

  return licenseBadge
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  let licensePicked = license
  let licenseLink = '';

  if (licensePicked === 'Apache 2.0'){
    licenseLink = `![Apache 2.0 License Link](https://opensource.org/licenses/Apache-2.0)`
  } else if(licensePicked === 'Eclipse'){
    licenseLink = `[Eclipse 2.0 License Link](https://opensource.org/licenses/EPL-2.0)`
  } else if(licensePicked === 'MIT'){
    licenseLink = `[MIT License Link](https://opensource.org/licenses/MIT)`
  }

  return licenseLink
};

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

function trueOrFalse(confirm) {
  if (confirm == true){
    return 'yes'
  }
  else {
    return 'no'
  }
}
// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {

  // generate Table of Contents based in user input
  let draftToCon = `## Table of Contents`;

  if (data.npminstall !== ''){ draftToCon += `
  * [Contact information](#contact);
  * [Installation](#npminstall);
  * [License](#license);
  * [Usage](#usage);
  * [Tests](#tests);
  * [Contributing](#contribute)`};

  return `# Project Title 🗂: ${data.title} ${renderLicenseBadge(data.license)}

## Contact information 📮:
Contact the Developer of this project via
* GitHub: ${data.github}
* email: ${data.email}

## Description 📜 
Brief overview: 
* ${data.description}

## Table of Contents

* [Contact information](#contact)
* [Installation](#npminstall)
* [License](#license)
* [Usage](#usage)
* [Tests](#tests)
* [Contributing](#contribute)


## License 🪪 and badge 🛡
The ${data.license} license has been selected for this project.

${renderLicenseBadge(data.license)}
${renderLicenseLink(data.license)}

## Motivation 💪🏻
We built this project ${data.motivation}

## What problem does it solve 🤷🏼? 
* ${data.problem}

## Installation 🛠
Follow these simple step-by-step instructions for installing the project code. 
1) Open in Terminal ${trueOrFalse(data.installT)} 
    \n Open in VS Code terminal ${trueOrFalse(data.installVs)}
2) Type in the installer code: npm install ${data.npminstall}

## Usage 🥡🥢
You can use this repository and code by: 
* ${data.usage}

## Links 💻 
Insert any links that you have used in this project:
* https:// ${data.links}

## Tests 🧪⚗️🧑🏾‍🔬
Tests that have been carried out on this project are:
* ${data.tests}

## Contributing 💃🏻🕺🏼 
You can contribute to this repository by ${data.contribute}

## Further Questions and Issues 🚨
Any issues with this repository please contact the repository owner via email at ${data.email} or via their GitHub repo ${data.github}.


#### This README file has been generated by FeedTheRead 🥙😋🗒 created by Adela Kobic 🙋🏻‍♀️
`;
}

module.exports = generateMarkdown;
